/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class AccessTokenSchema extends BaseModel {
  static $columns = ['abilities', 'createdAt', 'expiresAt', 'hash', 'id', 'lastUsedAt', 'name', 'tokenableId', 'type', 'updatedAt'] as const
  $columns = AccessTokenSchema.$columns
  @column()
  declare abilities: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.dateTime()
  declare expiresAt: DateTime | null
  @column()
  declare hash: string
  @column({ isPrimary: true })
  declare id: number
  @column.dateTime()
  declare lastUsedAt: DateTime | null
  @column()
  declare name: string | null
  @column()
  declare tokenableId: number
  @column()
  declare type: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class DriverSchema extends BaseModel {
  static $columns = ['createdAt', 'deletedAt', 'driverAddress', 'driverCity', 'driverCountry', 'driverEmail', 'driverLicenseExpiryDate', 'driverLicenseNumber', 'driverName', 'driverPassword', 'driverPhone', 'driverRole', 'driverState', 'id', 'updatedAt'] as const
  $columns = DriverSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.dateTime()
  declare deletedAt: DateTime | null
  @column()
  declare driverAddress: string | null
  @column()
  declare driverCity: string | null
  @column()
  declare driverCountry: string | null
  @column()
  declare driverEmail: string
  @column()
  declare driverLicenseExpiryDate: string
  @column()
  declare driverLicenseNumber: string
  @column()
  declare driverName: string
  @column()
  declare driverPassword: string
  @column()
  declare driverPhone: string
  @column()
  declare driverRole: string | null
  @column()
  declare driverState: string | null
  @column({ isPrimary: true })
  declare id: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class FinancialAnalistSchema extends BaseModel {
  static $columns = ['createdAt', 'deletedAt', 'financialAnalistAddress', 'financialAnalistCity', 'financialAnalistCountry', 'financialAnalistEmail', 'financialAnalistName', 'financialAnalistPassword', 'financialAnalistPhone', 'financialAnalistRole', 'financialAnalistState', 'id', 'isActive', 'updatedAt'] as const
  $columns = FinancialAnalistSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.dateTime()
  declare deletedAt: DateTime | null
  @column()
  declare financialAnalistAddress: string | null
  @column()
  declare financialAnalistCity: string | null
  @column()
  declare financialAnalistCountry: string | null
  @column()
  declare financialAnalistEmail: string
  @column()
  declare financialAnalistName: string
  @column()
  declare financialAnalistPassword: string
  @column()
  declare financialAnalistPhone: string
  @column()
  declare financialAnalistRole: string | null
  @column()
  declare financialAnalistState: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare isActive: boolean | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class FleetManagerSchema extends BaseModel {
  static $columns = ['address', 'city', 'country', 'createdAt', 'deletedAt', 'email', 'fullName', 'id', 'password', 'phoneNumber', 'role', 'state', 'updatedAt'] as const
  $columns = FleetManagerSchema.$columns
  @column()
  declare address: string | null
  @column()
  declare city: string | null
  @column()
  declare country: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.dateTime()
  declare deletedAt: DateTime | null
  @column()
  declare email: string
  @column()
  declare fullName: string
  @column({ isPrimary: true })
  declare id: number
  @column({ serializeAs: null })
  declare password: string
  @column()
  declare phoneNumber: string
  @column()
  declare role: string | null
  @column()
  declare state: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class SafetyOfficerSchema extends BaseModel {
  static $columns = ['createdAt', 'deletedAt', 'id', 'isActive', 'safetyOfficerAddress', 'safetyOfficerCity', 'safetyOfficerCountry', 'safetyOfficerEmail', 'safetyOfficerName', 'safetyOfficerPassword', 'safetyOfficerPhone', 'safetyOfficerRole', 'safetyOfficerState', 'updatedAt'] as const
  $columns = SafetyOfficerSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.dateTime()
  declare deletedAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare isActive: boolean | null
  @column()
  declare safetyOfficerAddress: string | null
  @column()
  declare safetyOfficerCity: string | null
  @column()
  declare safetyOfficerCountry: string | null
  @column()
  declare safetyOfficerEmail: string
  @column()
  declare safetyOfficerName: string
  @column()
  declare safetyOfficerPassword: string
  @column()
  declare safetyOfficerPhone: string
  @column()
  declare safetyOfficerRole: string | null
  @column()
  declare safetyOfficerState: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class UserSchema extends BaseModel {
  static $columns = ['createdAt', 'driverId', 'email', 'financialAnalystId', 'fleetManagerId', 'fullName', 'id', 'isActive', 'mobile', 'password', 'safetyOfficerId', 'updatedAt', 'userType'] as const
  $columns = UserSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare driverId: number | null
  @column()
  declare email: string
  @column()
  declare financialAnalystId: number | null
  @column()
  declare fleetManagerId: number | null
  @column()
  declare fullName: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare isActive: boolean | null
  @column()
  declare mobile: string | null
  @column({ serializeAs: null })
  declare password: string
  @column()
  declare safetyOfficerId: number | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userType: string | null
}
