/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  AccessTokens: () => import('#controllers/access_tokens_controller'),
  NewAccount: () => import('#controllers/new_account_controller'),
  Permissions: () => import('#controllers/permissions_controller'),
  Profile: () => import('#controllers/profile_controller'),
  Roles: () => import('#controllers/roles_controller'),
  Users: () => import('#controllers/users_controller'),
}
