export const messages = {
  ROLE_CREATED_SUCCESSFULLY: 'Role created successfully',
  ROLE_UPDATED_SUCCESSFULLY: 'Role updated successfully',
    ROLE_DELETED_SUCCESSFULLY: 'Role deleted successfully',
    ROLE_NOT_FOUND: 'Role not found',
    ROLE_ALREADY_EXISTS: 'Role already exists',
    PERMISSION_NOT_FOUND: 'Permission not found',
    PERMISSION_ALREADY_EXISTS: 'Permission already exists',
    PERMISSION_CREATED_SUCCESSFULLY: 'Permission created successfully',
    PERMISSION_UPDATED_SUCCESSFULLY: 'Permission updated successfully',
    PERMISSION_DELETED_SUCCESSFULLY: 'Permission deleted successfully',
    PERMISSION_ASSIGNED_SUCCESSFULLY: 'Permission assigned successfully',
    PERMISSION_REMOVED_SUCCESSFULLY: 'Permission removed successfully',
    common_messages_record_deleted: 'Record deleted successfully',
    common_messages_record_not_found: 'Record not found',
    common_messages_record_already_exists: 'Record already exists',
    common_messages_record_created: 'Record created successfully',
    common_messages_record_updated: 'Record updated successfully',
    common_messages_record_fetch_success: 'Record fetched successfully',
    common_messages_record_fetch_error: 'Error fetching record',
    common_messages_record_fetch_not_found: 'Record not found',
    common_messages_record_fetch_already_exists: 'Record already exists',
    common_messages_record_fetch_created: 'Record created successfully',
    common_messages_record_fetch_updated: 'Record updated successfully',
}